name: Deploy Stage (Development Version)

on: [push, pull_request]

env:
  VERSION: 1.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checking the Repo
        uses: actions/checkout@v4
      - name: Install Node 20
        uses: actions/setup-node@v4
      - name: Install Node Packages
        run: yarn install
      - name: Build Website
        run: yarn build
      - name: Specify Version
        run: echo $VERSION > dist/version.html
      - name: Set AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy on S3 Bucket
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_BUCKET_STAGE_ID }} --delete
          curl ${{ secrets.AWS_BUCKET_STAGE_PUBLIC_URL }} | grep "Web Map Application"
          curl ${{ secrets.AWS_BUCKET_STAGE_PUBLIC_URL }} | grep $APP_VERSION
