name: Test and Coverage Report

on: [push, pull_request]

env:
  VERSION: 1.0.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking the Repo
        uses: actions/checkout@v4
      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node Packages
        run: yarn install
      - name: Test for Lint
        run: yarn lint
      - name: Test for Application
        run: yarn test
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN}}
      - name: Build Website
        run: yarn build
      - name: Specify Version
        run: echo $VERSION > dist/version.html
      - name: Test the Built Website
        run: |
          yarn global add serve
          serve -s dist &
          sleep 10
          curl http://localhost:3000 | grep "Web Map Application"
